theme: jekyll-theme-hacker
title: Michael Qin
description: Director of Technology at Charles Schwab. Certified Architect and Egineer on AWS and Google Cloud.
markdown: kramdown
author:
  name: Michael Qin
  email: mike.qin@gmail.com
show_downloads: false
github: [metadata]
