theme: jekyll-theme-hacker
title: Michael Qin
description: Director of Technology at Charles Schwab. Certified Architect and Egineer on AWS and Google Cloud.
show_downloads: false
github:
  is_project_page: false
